apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pv-claim
  namespace: bigdata
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
