---
apiVersion: v1
kind: Service
metadata:
  name: metastore-db
  namespace: bigdata
spec:
  ports:
  - port: 13306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bigdata
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mariadb
        image: "mariadb/server:latest"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-for-hive
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "2Gi"
            cpu: 2
          limits:
            memory: "4Gi"
            cpu: 3
      volumes:
      - name: mariadb-for-hive
        persistentVolumeClaim:
          claimName: maria-pv-claim
