apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: test-application-airflow
  namespace: bigdata
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  timeToLiveSeconds: 40
  image: "guisilveira/test-application-spark"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/test-application.py
  sparkVersion: "3.2.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.2.1
    serviceAccount: jupyterhub
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.2.1
